### ISSUE TITLE
Redis integration

### ISSUE THREAD

**Issue by hysrx** [hysrx/ReiX#3]
### Reasoning
Using `config.json`, while human readable, is fine. But, Redis is one of the few NoSQL databases with support for low end devices such as the Raspberry Pi Zero. Also, .json files aren't databases and high-volume read/writes will cause an overlapping error eventually.

### Task Checklist

- [x]  Getting Redis up and running on a Raspberry Pi Zero
- [x]  Get documentation and learn
- [x]  Start implementing code
